basic solution
mate-academy/jv-spring-rest-web-practice pull request #26
Opened 2021-06-24 00:25 UTC by IhorRome

2021-06-24 09:52 UTC, Reastador approved these changes

2021-06-24 11:10 UTC, MaliukDaria requested changes

2021-06-24 11:10 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/controller/ShoppingCartController.java
> +        return "Movie session successfully added to users shopping cart";
Lets make this method void or return updated shopping cart

2021-06-24 11:10 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/validation/impl/EmailValidator.java
> +        return matcher.matches();
```suggestion
          return email != null && email.matches(EMAIL_PATTERN);
```

2021-06-24 14:34 UTC, MaliukDaria requested changes

2021-06-24 14:34 UTC, MaliukDaria commented on src/main/java/mate/academy/spring/controller/AuthenticationController.java
> +    public UserResponseDto register(@RequestBody UserRequestDto request) {
We still need to add @Valid annotation in front of UserRequestDto

2021-06-25 06:20 UTC, MaliukDaria approved these changes
Good job!

2024-10-14 08:49 UTC, closed without merging