Hw 38 jv spring rest web practice
mate-academy/jv-spring-rest-web-practice pull request #408
Opened 2023-02-01 16:29 UTC by SichniyAndriy

2023-02-01 20:25 UTC, aaananas requested changes

2023-02-01 20:25 UTC, aaananas commented on src/main/java/mate/academy/spring/controller/OrderController.java
> +    @GetMapping("")
```suggestion
    @GetMapping
```

2023-02-01 20:25 UTC, aaananas commented on src/main/java/mate/academy/spring/model/dto/response/OrderResponseDto.java
> +    private List<Ticket> tickets;
```suggestion
    private List<Long> ticketIds;
```
you should not return entities

2023-02-01 20:25 UTC, aaananas commented on src/main/java/mate/academy/spring/model/dto/response/ShoppingCartResponseDto.java
> +    private List<Ticket> tickets;
```suggestion
    private List<Long> ticketIds;
```

2023-02-01 20:25 UTC, aaananas commented on src/main/java/mate/academy/spring/model/dto/request/OrderRequestDto.java
> +public class OrderRequestDto {
you dont need this class

2023-02-02 10:57 UTC, Rommelua approved these changes

2025-11-20 20:23 UTC, closed without merging