added controllers, mappers and DTOs for entities
mate-academy/jv-spring-rest-web-practice pull request #482
Opened 2023-04-30 15:31 UTC by BusyhinD

2023-04-30 16:28 UTC, kozhukhovsky requested changes

2023-04-30 16:28 UTC, kozhukhovsky commented on src/main/java/mate/academy/spring/controller/OrderController.java
> +@CrossOrigin(origins = "*")
No need for this annotation

2023-04-30 16:28 UTC, kozhukhovsky commented on src/main/java/mate/academy/spring/controller/OrderController.java
> +        user.setId(userId);
It is better to get the user from the service userService.get(userId)

2023-04-30 16:28 UTC, kozhukhovsky commented on src/main/java/mate/academy/spring/controller/OrderController.java
> +        user.setId(userId);
the same

2023-04-30 16:28 UTC, kozhukhovsky commented on src/main/java/mate/academy/spring/controller/ShoppingCartController.java
> +        user.setId(userId);
same

2023-04-30 16:28 UTC, kozhukhovsky commented on src/main/java/mate/academy/spring/controller/ShoppingCartController.java
> +        user.setId(userId);
same for movie session

2023-04-30 16:28 UTC, kozhukhovsky commented on src/main/java/mate/academy/spring/controller/ShoppingCartController.java
> +            @RequestBody MovieSessionRequestDto movieSessionRequestDto) {
```suggestion
            ) {
```

2023-05-01 10:04 UTC, uliana-andrushchuk requested changes

2023-05-01 10:04 UTC, uliana-andrushchuk commented on src/main/java/mate/academy/spring/controller/OrderController.java
> +            shoppingCartDtoRequestMapper;
This field is redundant.
I do not see usage of this `shoppingCartDtoRequestMapper` in this class

2023-05-01 16:42 UTC, olekskov approved these changes
Good job

2024-02-13 20:57 UTC, closed without merging