added java spring rest practice solution
mate-academy/jv-spring-rest-web-practice pull request #50
Opened 2021-08-20 23:17 UTC by Basilius-Third

It does not fully work, might need to fix lazy initialization problem. But now I'm too tired. Went to a vacation, bye

2021-08-23 09:57 UTC, aaananas approved these changes

2021-08-23 10:13 UTC, Sofasmile requested changes
one small comment

2021-08-23 10:13 UTC, Sofasmile commented on src/main/java/mate/academy/spring/service/UserService.java
> +    Optional<User> findById(Long id);
```suggestion
    User findById(Long id);
```

2021-08-25 09:16 UTC, Sofasmile approved these changes

2021-11-16 16:56 UTC, closed without merging